version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: public.ecr.aws/w7b0v2b2/brain-task
    CLUSTER_NAME: my-eks-cluster
  compute_type: BUILD_GENERAL1_SMALL

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon Public ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w7b0v2b2

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t brain-task .
      - docker tag brain-task:latest public.ecr.aws/w7b0v2b2/brain-task:latest
      - docker push public.ecr.aws/w7b0v2b2/brain-task:latest

  post_build:
    commands:
      - echo "Installing kubectl..."
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-02-12/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --name my-eks-cluster --region ap-south-1

      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - deployment.yaml
    - service.yaml
    - appspec.yml


